CREATE TABLE USUARIO(
	ID NUMBER NOT NULL,
	EMAIL VARCHAR2(11) NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	EMPRESA VARCHAR2(100) NOT NULL,
	TELEFONE VARCHAR2(11) NOT NULL,
	CELULAR VARCHAR2(11) NULL,
	WHATSAPP VARCHAR2(11) NULL,
	MODAL VARCHAR2(11) NOT NULL,
	CEP VARCHAR2(11) NULL,
	UF VARCHAR2(2) NOT NULL,
	CIDADE VARCHAR2(100) NOT NULL,
	BAIRRO VARCHAR2(200) NOT NULL,
	RUA VARCHAR2(200) NOT NULL,
	NUMERO NUMBER NOT NULL,
 CONSTRAINT USUARIO_PK PRIMARY KEY (ID) ENABLE
)